### ISSUE TITLE
Organização do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-SportLife#10]
Atribuições de cada papel pouco claras à equipe já que tanto o desenvolvedor back-end quanto o analista de teste possuem as mesmas responsabilidades. Houve uma separação entre analista de teste e analista CI ao invés de um único papel de DEV CI/TEST, além da discordância entre o que foi definido na planilha das equipes e o que está na entrega.

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/2ec3d7c4-e4a1-43bc-89e2-be9dd25a31e9)

**Comment by Bertolazi** [comment]
ajeitado de acordo com a planilha e as tarefas refeitas
