### ISSUE TITLE
Matriz de comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-SportLife#12]
Matriz de comunicação - copiado do template de visão do produto e projeto. 

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/dc6d7791-10a6-4566-8653-510816247604)

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/bbf2841a-d539-438f-afe9-0032ef46f824)

**Comment by Bertolazi** [comment]
foi alterado sem cópias
