### ISSUE TITLE
Gerenciamento de Riscos

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-SportLife#13]
Mais cópias...

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/dbb9095e-dfbd-45c0-a39b-cc08c40560a8)

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/4a33e6d4-c5ae-4e2b-92db-04501d77545d)

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/fd4515a4-aa6b-41ec-bda1-524b02ea7715)

**Comment by RufinoVfR** [comment]
Reescrevi o gerenciamento de riscos, deixando-o mais completo com explicações de cada ponto.
