### ISSUE TITLE
processo

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-SportLife#14]
mais cópias...

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/5382ccc8-9493-49fa-966c-78dcaed307e2)

![image](https://github.com/mdsreq-fga-unb/2023.2-SportLife/assets/68402547/147ef240-2182-413a-bca6-2a4719b81019)

**Comment by Bertolazi** [comment]
foi alterado sem cópias
