### ISSUE TITLE
Publicação Gitpages

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-SportLife#2]
A equipe não publicou de maneira adequada os resultados da unidade. 

A solicitação, registrada no plano de ensino e plano da unidade, é que os resultados sejam publicados, via **GitPages**, no repositório da disciplina, "https://**mdsreq-fga-unb.github.io**/...". 

A equipe deixou seus resultados em um fork do estudante Gabriel Basto Bertolazi: "https://bertolazi.github.io/2023.2-SportLife/#/".

**Comment by CaioPacheco** [comment]
Documentação colocada no Git Pages

**Comment by CaioPacheco** [comment]
@Bertolazi atualizou o git pages, usando o MK docs.
