### ISSUE TITLE
rascunho e revisão

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-SportLife#3]
A equipe registra apenas um rascunho e revisão. Essa, a revisão do rascunho é a entrega?

**Comment by CaioPacheco** [comment]
Aconteceram outras revisões anteriormente à entrega. Só consta a revisão final por conta de um erro de falta de comunicação da equipe. Redobraremos a atenção quanto a isso nas próximas entregas.
