### ISSUE TITLE
Objetivos do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-SportLife#7]
Muito genérico, precisa ser revisto.

"Facilitar o controle de **_informações relevantes_** para a clínica prestar seus serviços aos clientes de forma **_mais simples e direta_**. Através de disponibilizar conteúdo sobre nutrição infantil e a formação de um cronograma."

**Comment by Bertolazi** [comment]
mudança na descrição dos objetivos do produto
